# TODO: Add `github-action` ecosystem check when PR #171 lands

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    # Limit pull requests to 1 so Dependabot isn't constantly rebasing PRs.
    # https://github.com/python-poetry/poetry/issues/496
    open-pull-requests-limit: 1

  - package-ecosystem: "pip"
    directory: "/{{^cookiecutter.repo_name^}}"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    open-pull-requests-limit: 1

  - package-ecosystem: "npm"
    directory: "/{{^cookiecutter.repo_name^}}"
    schedule:
      interval: "weekly"
    target-branch: "develop"
