[tool.poetry]
name = "django-hydra"
version = "3.0"
description = "A generic project template for django"
authors = ["Ben Beecher <ben@lightmatter.com>"]

[tool.poetry.dependencies]
python = "^3.11"
cookiecutter = "^2.3.0"

[tool.poetry.group.dev.dependencies]
isort = "^5.12.0"
retrocookie = "^0.4.2"

[tool.poetry.group.docs.dependencies]
Sphinx = "^7.2.5"
furo = "^2023.9.10"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
