version: 2
jobs:
  build:
      docker:
        - image: circleci/python:3.6-stretch-node-browsers
      steps:
        - checkout
        - run: npm install webpack
        - run: npm install yarn
        - run: pip install --user cookiecutter
  test:
    docker:
      - image: circleci/python:3.6-stretch-node-browsers
      - image: circleci/postgres:10-alpine-postgis
        environment:
          POSTGRES_USER: genericapp
          POSTGRES_DB: genericapp
          DATABASE_URL: postgis://genericapp@localhost:5432/genericapp
      - image: circleci/redis
    working_directory: /home/circleci/project
    steps:
      - checkout
      - run:
          command: |
            echo 'export PATH=/home/circleci/.local/bin/:$PATH' >> $BASH_ENV
            source $BASH_ENV
      - run: sudo apt-get install -y postgresql-client
      - run: npm install webpack
      - run: npm install yarn
      - run: pip install --user cookiecutter
      - run: ./test.sh -t


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
