version: 2.1
orbs:
  python: circleci/python@1.5
  node: circleci/node@4.9.0
  slack: circleci/slack@4.5.1

jobs:
  test:
    docker:
      - image: cimg/python:3.10.1-browsers
      - image: cimg/14.0
        environment:
          POSTGRES_USER: sampleapp
          POSTGRES_DB: sampleapp
          DATABASE_URL: postgis://sampleapp@localhost:5432/sampleapp
      - image: cimg/redis

    working_directory: /home/circleci/project
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - node/install-packages
      - run: ./test.sh

      - slack/status:
          channel: "#project-template"
          only_for_branches: develop,master


workflows:
  version: 2.1
  test:
    jobs:
      - test:
          context: lightmatter
