version: 2.1
orbs:
  python: circleci/python@0.1
  node: circleci/node@1.1.6
  slack: circleci/slack@3.4.2

jobs:
  test:
    docker:
      - image: circleci/python:3.8-node-browsers
      - image: circleci/postgres:12-alpine-postgis-ram
        environment:
          POSTGRES_USER: sampleapp
          POSTGRES_DB: sampleapp
          DATABASE_URL: postgis://sampleapp@localhost:5432/sampleapp
      - image: circleci/redis

    working_directory: /home/circleci/project
    steps:
      - checkout
      - python/install-deps

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run: sudo apt-get install -y postgresql-client


      #TODO: test to make sure that create patch still works
      #TODO: test to make sure that a bad name isn't generated
      #TODO: make generate database more flexible so it doesn't fail  on circle
      - run: ./test.sh

      - slack/status:
          channel: "#project-template"
          only_for_branches: develop,master



workflows:
  version: 2.1
  test:
    jobs:
      - test:
          context: lightmatter
