version: 2.1
orbs:
  python: circleci/python@0.1
  node: circleci/node@1.1.6
  slack: circleci/slack@3.4.2

jobs:
  test:
    docker:
      - image: circleci/python:3.6-stretch-node-browsers
      - image: circleci/postgres:10-alpine-postgis
        environment:
          POSTGRES_USER: sampleapp
          POSTGRES_DB: sampleapp
          DATABASE_URL: postgis://sampleapp@localhost:5432/sampleapp
      - image: circleci/redis
        
    working_directory: /home/circleci/project
    steps:
      - checkout
      # todo figure out how to target the template's requirements
      # - python/load-cache
      # - python/install-deps
      # - run: pip install --user -r requirements-dev.txt
      # - python/save-cache

      - run:
          command: |
            echo 'export PATH=/home/circleci/.local/bin/:$PATH' >> $BASH_ENV
            source $BASH_ENV
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm install yarn
            - run: npm install webpack

            - run: npm run build

      - run: sudo apt-get install -y postgresql-client

      - run: pip install --user cookiecutter
      - run: ./test.sh 
      - slack/status:
          fail_only: true
          channel: "#project-template"
          only_for_branches: develop,master



workflows:
  version: 2.1
  build_and_test:
    jobs:
      - test:
          context: lightmatter
