version: 2.1
orbs:
  python: circleci/python@1.3.2
  node: circleci/node@3.0.1
  heroku: circleci/heroku@1.0.1
  codecov: codecov/codecov@3.2.2
  slack: circleci/slack@3.4.2
  test-runner: ghostinspector/test-runner@1.0.0
jobs:
  test-django:
    docker:
      - image: cimg/python:3.10.1-browsers
      - image: cimg/postgres:14.1
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: circle_test

      - image: cimg/redis:6.2.6
    environment:
      DATABASE_URL: "psql://ubuntu:@localhost/circle_test"
      DJANGO_SETTINGS_MODULE: {{cookiecutter.repo_name}}.config.settings.test
      DJANGO_SECRET_KEY: "!!!! Change me !!!!"
      DJANGO_DEBUG: False
      REDIS_URL: redis://localhost:6379

    working_directory: /home/circleci/project
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: npm run build
      - python/install-packages:
          pkg-manager: poetry
      - run: poetry run pre-commit run --all-files
      - run: poetry run playwright install
      - run: poetry run coverage run --source='.' -m pytest
      - store_test_results:
          path: test_reports
      - run: poetry run coverage xml
      - codecov/upload
      - slack/status:
          fail_only: true
          channel: "#{{cookiecutter.repo_name}}-internal"
          only_for_branches: develop,main

  sentry: #issue a new sentry release
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run: curl -sL https://sentry.io/get-cli/ | bash # install sentry cli
      - run: sentry-cli releases new -p {{cookiecutter.repo_name}} $CIRCLE_SHA1
      - run: sentry-cli releases set-commits --auto $CIRCLE_SHA1
      - run: sentry-cli releases finalize $CIRCLE_SHA1


workflows:
  version: 2.1
  deploy:
    jobs:
      - test-django:
          context: lightmatter

      # - sentry:
      #     name: sentry-prod
      #     context: lightmatter
      #     requires:
      #       - deploy-prod
      #     filters:
      #       branches:
      #         only: main

      # - sentry:
      #     name: sentry-dev
      #     context: lightmatter
      #     requires:
      #       - deploy-dev
      #     filters:
      #       branches:
      #         only: develop




      # - ghostinspector:
      #     context: lightmatter
      #     requires:
      #       - deploy-dev
