version: 2.1
orbs:
  python: circleci/python@0.1
  node: circleci/node@1.1.6
  heroku: circleci/heroku@1.0.1
  codecov: codecov/codecov@1.0.5
  slack: circleci/slack@3.4.2
  test-runner: ghostinspector/test-runner@1.0.0
jobs:
  test:
    docker:
      - image: circleci/python:3.8-stretch-node-browsers
      - image: circleci/postgres:10.1-alpine-postgis
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: circle_test
      - image: circleci/redis

    environment:
      DJANGO_SETTINGS_MODULE: {{cookiecutter.repo_name}}.{{cookiecutter.repo_name}}.settings.circleci

    working_directory: /home/circleci/project

    steps:
      - checkout

      - python/load-cache
      - run: sudo apt-get update && sudo apt-get install -y gdal-bin python-gdal python3-gdal
      - python/install-deps
      - python/save-cache
      - run: pip install --user -r requirements-dev.txt

      - node/with-cache:
          steps:
            - run: yarn install --frozen-lockfile
            - run: yarn install webpack
            - run: yarn run build

      - run: scripts/validate.sh
      - run: yarn run test
      - run: coverage run --source='.' manage.py test
      - store_test_results:
          path: test_reports
      - codecov/upload
      - slack/status:
          fail_only: true
          channel: "#{{cookiecutter.repo_name}}-internal"
          only_for_branches: develop,master

  deploy:
    parameters:
      app-name:
        description: destination app
        type: string
        default: {{cookiecutter.repo_name}}-dev
    docker:
      - image: cimg/base:2020.01
    working_directory: /home/circleci/project
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          app-name: << parameters.app-name >>
      - slack/status:
          channel: "#{{cookiecutter.repo_name}}-internal"

  # ghostinspector:
  #   docker:
  #     - image: cimg/base:2020.01
  #   steps:
  #     - test-runner/execute-suite:
  #         start-url: '<URL GOES HERE>'
  #         id: ID_GOES_HERE

workflows:
  version: 2.1
  test:
    jobs:
      - test:
          context: lightmatter

      - deploy:
          name: deploy-dev
          context: lightmatter
          app-name: {{cookiecutter.repo_name}}-dev
          requires:
            - test
          filters:
            branches:
              only: develop

      - deploy:
          name: deploy-staging
          context: lightmatter
          app-name: {{cookiecutter.repo_name}}-staging
          requires:
            - test
          filters:
            branches:
              only: staging

      - deploy:
          name: deploy-prod
          context: lightmatter
          app-name: {{cookiecutter.repo_name}}-prod
          requires:
            - test
          filters:
            branches:
              only: master

      # - ghostinspector:
      #     context: lightmatter
      #     requires:
      #       - deploy-dev
