#!/bin/bash
set -e
cd /app/
PID=/app/gunicorn.pid

if [ -f $PID ]; then rm $PID; fi

if [[ "$ENVIRONMENT" -eq "local" ]]; then
    exec python3.8 manage.py runserver 0.0.0.0:8000
else
    exec gunicorn {{cookiecutter.repo_name}}.{{cookiecutter.repo_name}}.asgi:application --bind 0.0.0.0:8000  -k uvicorn.workers.UvicornWorker --pid=$PID --access-logfile - --preload
fi
