FROM node:14 as intermediate

RUN mkdir /npm-packages
COPY package.json /npm-packages/
RUN curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.0
RUN cd /npm-packages && yarn install

FROM node:14

COPY --from=intermediate /npm-packages /npm-packages
ENV PATH /npm-packages/node_modules/.bin:${PATH}
ENV NODE_PATH /npm-packages/node_modules
RUN mkdir /src
WORKDIR /src
