version: '2.2'
services:
  web:
    image: "nginx:1.17"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "{{ cookiecutter.local_port }}:80"
    depends_on:
      - frontend
      - backend

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    command: "npm run dev"
    volumes:
      - .:/src

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    depends_on:
      - db
      - redis
    env_file: .env
    volumes:
      - .:/src

  db:
    image: "postgres:12.2"
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql

  redis:
    image: "redis:5"

volumes:
  postgres-data:
