# This docker-compose.yml file is used to set up your project in the local
# development environment *only*. It is *not* used in deployment to our cloud
# servers, and has no effect whatsoever in cloud deployments.
#
# See our Developer Handbook for more information:
# http://docs.divio.com/en/latest/reference/docker-docker-compose.html
version: "3.6"
services:
  ui:
    build:
      context: "."
      target: next
    command: yarn run next start
    depends_on:
      - web
    links:
      - "web:web"
    volumes:
      - ".:/app/"
    ports:
      - "3000:3000"
  web:
    build:
      context: "."
      target: dev
      args:
        DATABASE_URL: "psql://{{cookiecutter.repo_name}}:{{cookiecutter.repo_name}}@db/{{cookiecutter.repo_name}}"
    command: pipenv run ./manage.py runserver_plus 0.0.0.0:8000
    depends_on:
      - db
    links:
      - "db:db"
    ports:
      - "8000:8000"
    environment:
      - ALLOWED_HOSTS="*"
      - SECRET_KEY="foobar"
      - DATABASE_URL=psql://{{cookiecutter.repo_name}}:{{cookiecutter.repo_name}}@db/{{cookiecutter.repo_name}}
      - DJANGO_SETTINGS_MODULE={{cookiecutter.repo_name}}.config.settings.local
      - API_BASE_URL=
      - PORT=4000
      - ENVIRONMENT=local
    volumes:
      - ".:/app/"
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: "{{cookiecutter.repo_name}}"
      POSTGRES_USER: "{{cookiecutter.repo_name}}"
      POSTGRES_PASSWORD: "{{cookiecutter.repo_name}}"
