[tool.poetry]
name = "{{cookiecutter.repo_name}}"
version = "0.1.0"
description = ""
authors = ["Ben Beecher <Ben@lightmatter.com>"]

[tool.poetry.dependencies]
python = "^3.9"
django-environ = "^0.8.1"
psycopg2-binary = "^2.9.1"
django-extensions = "^3.1.3"
django-model-utils = "^4.2.0"
boto3 = "^1.19.7"
django-storages = "^1.12.3"
uvicorn = "^0.16.0"
gunicorn = "^20.1.0"
sentry-sdk = "^1.4.3"
Django = "^4.0"
whitenoise = {extras = ["brotli"], version = "^5.3.0"}
django-allauth = "^0.47.0"
django-htmx = "^1.6.0"
django-annoying = "^0.10.6"
Pillow = "^8.4.0"
django-anymail = {extras = ["sendgrid"], version = "^8.4"}
django-vite = "^1.2.1"
django-components = "^0.17"

[tool.poetry.dev-dependencies]
ipython = "^7.29.0"
ipdb = "^0.13.9"
pdbpp = "^0.10.3"
ptpython = "^3.0.20"
isort = "^5.9.3"
black = "^21.9b0"
django-debug-toolbar = "^3.2.2"
model-bakery = "^1.3.3"
coverage = "^6.1.1"
watchdog = "*"
pylint-django = "==2.4.4"
Werkzeug = "*"
bandit = "*"
honcho = "*"
flake8 = "==3.8.4"
flake8-polyfill = "==1.0.2"
unittest-xml-reporting = "^3.0.4"
playwright = "^1.17.2"
prospector = "^1.5.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
