[tool.poetry]
name = "{{cookiecutter.repo_name}}"
version = "0.1.0"
description = ""
authors = ["Ben Beecher <Ben@lightmatter.com>"]

[tool.poetry.dependencies]
python = "^3.9"
django-environ = "^0.8.1"
psycopg2-binary = "^2.9.1"
django-extensions = "^3.1.3"
django-model-utils = "^4.2.0"
boto3 = "^1.19.7"
django-storages = "^1.12.3"
uvicorn = "^0.16.0"
gunicorn = "^20.1.0"
sentry-sdk = "^1.4.3"
Django = {extras = ["argon2"], version = "^4.0"}
whitenoise = {extras = ["brotli"], version = "^5.3.0"}
django-allauth = "^0.47.0"
django-htmx = "^1.6.0"
django-annoying = "^0.10.6"
Pillow = "^8.4.0"
django-anymail = {extras = ["sendgrid"], version = "^8.4"}
django-vite = "^1.2.1"
django-components = "^0.17"
tblib = "^1.7.0"
django-cachalot = "^2.4.5"

[tool.poetry.dev-dependencies]
ipython = "^7.29.0"
ipdb = "^0.13.9"
pdbpp = "^0.10.3"
ptpython = "^3.0.20"
django-debug-toolbar = "^3.2.2"
model-bakery = "^1.3.3"
coverage = "^6.1.1"
watchdog = "*"
pylint-django = "==2.4.4"
Werkzeug = "*"
bandit = "*"
honcho = "*"
unittest-xml-reporting = "^3.0.4"
playwright = "^1.17.2"
pywatchman = "^1.4.1"
icecream = "^2.1.1"
pre-commit = "^2.16.0"
flake8 = "3.9.2"
flakehell = "^0.9.0"
flake8-bandit = "^2.1.2"
flake8-bugbear = "^21.11.29"
flake8-builtins = "^1.5.3"
flake8-eradicate = "^1.2.0"
flake8-mutable = "^1.2.0"
flake8-django = "^1.1.2"
black = "^21.12b0"
isort = "^5.10.1"

[tool.black]
line-length = 92
target-version = ['py310']
include = '\.pyi?$'
exclude = '''
(
  /migrations/
)
'''

[tool.isort]
line_length = "92"
multi_line_output = "3"
include_trailing_comma = "True"
use_parentheses = "True"
combine_as_imports = "True"
skip_glob = "*migrations/*.py"
known_standard_library = "django"
known_third_party = "django.contrib,django.utils"

[tool.ipdb]
context = 10

[tool.flakehell]
exclude = ["README.rst", "README.md", "*/settings/*", "*/migrations/*"]
format = "colored"
max_line_length = 92
show_source = true
extended_default_ignore=[]  # https://github.com/flakehell/flakehell/issues/10#issuecomment-822720074

[tool.flakehell.plugins]
flake8-bandit = ["+*", "-S322"]
flake8-bugbear = ["+*"]
flake8-builtins = ["+*"]
flake8-comprehensions = ["+*"]
flake8-django = ["+*"]
flake8-eradicate = ["+*"]
flake8-mutable = ["+*"]
mccabe = ["+*"]
pep8-naming = ["+*"]
pycodestyle = ["+*", "-W503"]
pyflakes = ["+*"]
pylint = ["+*"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
